name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3  # Updated to v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # You can also try removing this if issues persist
    
    - run: npm ci  # Using ci instead of install for more reliable builds
    - run: npm start
